// src/components/resume/contact-information.tsx
import SectionHeader from "./section-header"

export default function ContactInformation() {
  return (
    <>
      <SectionHeader>Contact Information</SectionHeader>
      <ul className="list-disc list-inside">
        <li>
          Email:{" "}
          <a
            className="text-blue-700 underline"
            href="mailto:jon.willesen@gmail.com"
          >
            jon.willesen@gmail.com
          </a>
        </li>
        <li>
          Phone:{" "}
          <a className="text-blue-700 underline" href="tel:801-381-4176">
            801-381-4176
          </a>
        </li>
        <li>
          LinkedIn:{" "}
          <a
            className="text-blue-700 underline"
            href="https://www.linkedin.com/in/jonwillesen"
          >
            https://www.linkedin.com/in/jonwillesen
          </a>
        </li>
      </ul>
    </>
  )
}

// src/routes/resume/contact-information.svelte
<dl class="xs:grid-cols-[auto_1fr] grid grid-cols-1 gap-x-4">
  <dt class="xs:text-right">Email</dt>
  <dd>
    <a class="anchor" href="mailto:jon.willesen@gmail.com"
      >jon.willesen@gmail.com</a
    >
  </dd>

  <dt class="xs:text-right">Phone</dt>
  <dd><a class="anchor" href="tel:+18013814176">(801) 381-4176</a></dd>

  <dt class="xs:text-right">LinkedIn</dt>
  <dd>
    <a
      class="anchor"
      target="_blank"
      href="https://www.linkedin.com/in/jonwillesen"
      >linkedin.com/in/jonwillesen</a
    >
  </dd>

  <dt class="xs:text-right">GitHub</dt>
  <dd>
    <a class="anchor" target="_blank" href="https://github.com/jwillesen"
      >github.com/jwillesen</a
    >
  </dd>
</dl>
