// components/resume/skills.tsx
import SectionHeader from './section-header'

export interface Skill {
  title: string
  keywords: string[]
}

export const skills: Skill[] = [
  {
    title: 'Featured',
    keywords: ['JavaScript', 'TypeScript', 'React', 'Node'],
  },
  {
    title: 'Languages and Frameworks',
    keywords: ['Ruby', 'Ruby on Rails', 'SQL', 'C++'],
  },
  {
    title: 'Technologies',
    keywords: [
      'Git',
      'Docker',
      'PostgreSQL',
      'Next.js',
      'Webpack',
      'Jest',
      'Redux',
      'Recoil',
      'Pullstate',
      'Tailwind CSS',
      'Lambda',
      'Rest',
      'GraphQL',
      'Apollo',
    ],
  },
  {
    title: 'Other Keywords',
    keywords: [
      'SaaS',
      'Accessibility',
      'Aria',
      'Frontend',
      'Backend',
      'Full Stack',
      'Serverless',
      'Automated Testing',
      'Agile',
      'Scrum',
      'OOP',
      'HTML',
      'CSS',
      'JSON',
      'XML',
    ],
  },
]

export default function Skills() {
  return (
    <>
      <SectionHeader>Skills</SectionHeader>
      {skills.map(({ title, keywords }) => (
        <div key={title}>
          <h4 className="font-semibold my-1">{title}</h4>
          <div className="grid grid-cols-4 ml-5">
            {keywords.map(keyword => (
              <div key={keyword}>{keyword}</div>
            ))}
          </div>
        </div>
      ))}
    </>
  )
}

// src/routes/resume/skills.svelte
<div class="flex flex-col gap-4">
  <div>
    <h4 class="h4">Languages</h4>
    <p>JavaScript, TypeScript, HTML, CSS, SQL, JSON</p>
  </div>

  <div>
    <h4 class="h4">Frameworks & Libraries</h4>
    <p>React, Svelte, SvelteKit, Node.js, Tailwind CSS, Apollo GraphQL</p>
  </div>

  <div>
    <h4 class="h4">Tools & Platforms</h4>
    <p>Git, AWS Lambda, REST APIs, GraphQL, Vite, Webpack</p>
  </div>

  <div>
    <h4 class="h4">Testing & Best Practices</h4>
    <p>
      Jest, Vitest, Accessibility (ARIA, WCAG 2.1 AA Compliance), End-to-End
      (E2E) Testing (Cypress, Playwright), Agile/Scrum Methodologies
    </p>
  </div>

  <div>
    <h4 class="h4">Other Expertise</h4>
    <p>
      Component Libraries, Progressive Web App (PWA) Development, SaaS
      Platforms, Front-End Architecture, Back-End Integration, Object-Oriented
      Programming (OOP), Automated Testing
    </p>
  </div>
</div>

<style>
  p {
    margin-left: var(--spacing-4);
  }
</style>
